fos_rest:
    disable_csrf_role: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
    view:
        view_response_listener: force
        formats:
            json: true
            xml:  false
#    routing_loader:
#        default_format: json
    serializer:
        serialize_null: true
    param_fetcher_listener: true
    body_listener: true
    access_denied_listener:
        json: true
    exception:
        messages:
            'Symfony\Component\HttpKernel\Exception\HttpException': true
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': true
