jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: false
        directories:
            App:
                namespace_prefix: "App"
                path: "%kernel.root_dir%/Serializer"
    property_naming:
        separator:  ~
        lower_case: true
    handlers:
        datetime:
            default_format: 'Y-m-d\TH:i:sO'
            default_timezone: 'UTC'